# 4 TO - DO - Task

## 4.1 Exercise on Functions:

### **Task - 1:**

Create a Python program that converts between different units of measurement.

• The program should:
  1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
  2. Ask the user to input the value to be converted.
  3. Perform the conversion and display the result.
  4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. **Functions**: Define at least one function to perform the conversion.
2. **Error Handling**: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. **User Input**: Prompt the user to select the conversion type and input the value.
4. **Docstrings**: Include a docstring in your function to describe its purpose, parameters, and
return value.


• Conversion Options:
1. **Length**:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. **Weight**:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. **Volume**:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (int): The type of conversion selected by the user.
    value (float): The numeric value to be converted.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:
        return value * 3.28084  # meters to feet
    elif conversion_type == 2:
        return value / 3.28084  # feet to meters
    elif conversion_type == 3:
        return value * 2.20462  # kg to pounds
    elif conversion_type == 4:
        return value / 2.20462  # pounds to kg
    elif conversion_type == 5:
        return value * 0.264172  # liters to gallons
    elif conversion_type == 6:
        return value / 0.264172  # gallons to liters
    else:
        return None


print("Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Select conversion type (1-6): "))
    value = float(input("Enter the value to convert: "))

    result = convert_units(choice, value)

    if result is None:
        print("Unsupported conversion type.")
    else:
        print("Converted value:", result)

except ValueError:
    print("Error: Please enter a valid numeric value.")

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Select conversion type (1-6): 4
Enter the value to convert: 100
Converted value: 45.35929094356398


### **Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.

**• The Program should:**
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

**• Requirements:**

1. **Functions**: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. **Error Handling**: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. **User Input**: Prompt the user to select the operation and input the list of numbers.
4. **Docstrings**: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)


print("Math Operations on a List")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = int(input("Choose an operation (1-4): "))

    user_input = input("Enter numbers separated by spaces: ")

    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("The list cannot be empty.")

    if choice == 1:
        print("Sum:", find_sum(numbers))
    elif choice == 2:
        print("Average:", find_average(numbers))
    elif choice == 3:
        print("Maximum:", find_maximum(numbers))
    elif choice == 4:
        print("Minimum:", find_minimum(numbers))
    else:
        print("Invalid operation selected.")

except ValueError:
    print("Error: Please enter valid numbers.")

Math Operations on a List
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 1
Enter numbers separated by spaces: 6 7 8 9
Sum: 30.0


## 4.2 Exercise on List Manipulation:


### **1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

**• Requirements:**

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[0::2]

numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print(result)

[1, 3, 5]


### **2. Slice a Sublist**:


Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

**• Requirements:**

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from index 'start' to 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): The starting index.
    end (int): The ending index.

    Returns:
    list: A sublist containing elements from start to end (inclusive).
    """
    return lst[start:end+1]

numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print(result)

[3, 4, 5]


### **3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

**• Requirements:**

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]

numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print(result)

[5, 4, 3, 2, 1]


### **4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

**• Requirements:**

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print(result)

[2, 3, 4]


### **5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

**• Requirements:**

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract.

    Returns:
    list: A list containing the first n elements.
    """
    return lst[:n]


numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print(result)

[1, 2, 3]


### **6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

**• Requirements:**

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A list containing the last n elements.
    """
    return lst[-n:]


numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print(result)

[4, 5]


### **7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

**• Requirements:**

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Returns every second element from the list starting from the
    second-to-last element and moving backward.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A list containing elements in reverse order skipping one element.
    """
    return lst[-2::-2]


numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print(result)

[5, 3, 1]


## 4.3 Exercise on Nested List:

### **1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

**• Requirements:**

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list containing sublists.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []

    for sublist in lst:
        for item in sublist:
            flat_list.append(item)

    return flat_list

numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)

print(result)

[1, 2, 3, 4, 5]


### **2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

**• Requirements:**

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Accesses an element in a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices to traverse the nested list.

    Returns:
    The element at the specified position.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print(result)

6


### **3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

**• Requirements:**

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): The nested list containing numbers or sublists.

    Returns:
    int/float: The sum of all numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # recursive call for sublist
        else:
            total += item
    return total

numbers = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(numbers)

print(result)

21


### **4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

**• Requirements:**

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem : The element to remove.

    Returns:
    list: The modified list with the element removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            # Recursively remove elem from sublist
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)
    return result


nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2

result = remove_element(nested_list, element_to_remove)
print(result)

[[1], [3], [4, 5]]


### **5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

**• Requirements:**

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list regardless of depth.

    Parameters:
    lst (list): The nested list containing numbers or sublists.

    Returns:
    int/float: The maximum number in the nested list.
    """
    max_val = None

    for element in lst:
        if isinstance(element, list):
            current_val = find_max(element)
        else:
            current_val = element

        # If current_val is None (empty sub-list), skip it
        if current_val is None:
            continue

        # If max_val hasn't been set yet, or we found a bigger number
        if max_val is None or current_val > max_val:
            max_val = current_val

    return max_val


numbers = [[1, 2], [3, [4, 5]], 6]
result = find_max(numbers)

print(result)

6


### **6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

**• Requirements:**

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts the number of times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem : The element to count.

    Returns:
    int: The number of occurrences of elem in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recursively count in sublist
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


# Example
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2

result = count_occurrences(nested_list, element_to_count)
print(result)

3


### **7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

**• Requirements:**

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].



In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list regardless of depth.

    Parameters:
    lst (list): A nested list containing sublists at any depth.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)
    return flat_list


# Example
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


### **8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

**• Requirements:**

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all numbers in a nested list.

    Parameters:
    lst (list): A nested list containing numbers or sublists.

    Returns:
    float: The average of all numbers in the nested list.
    """
    def flatten_and_sum(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                sub_total, sub_count = flatten_and_sum(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = flatten_and_sum(lst)
    if total_count == 0:
        return 0  # avoid division by zero
    return total_sum / total_count


nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print(result)

3.5


---
# NumPy

## 10.1 Basic Vector and Matrix Operation with Numpy.

### **Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), fill_value=7, dtype=int)
print("\n3x3 array filled with 7:\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
sample_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros array with same shape/type as sample_array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("\nOnes array with same shape/type as sample_array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy array from list:\n", numpy_array)

Empty 2x2 array:
 [[3.9276835e-315 0.0000000e+000]
 [5.7580742e-317 5.7620742e-317]]

All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array with same shape/type as sample_array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones array with same shape/type as sample_array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Numpy array from list:
 [1 2 3 4]


### **Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**


Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array 10 to 49:\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n3x3 matrix 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\n3x3 identity matrix:\n", identity_3x3)

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_random_30 = random_array_30.mean()
print("\nRandom array of size 30:\n", random_array_30)
print("Mean of random array:", mean_random_30)

# 5. Create a 10x10 array with random values and find min & max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n10x10 random array:\n", random_10x10)
print("Min:", min_val, "Max:", max_val)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1  # 5th element has index 4
print("\nZero array with 5th element as 1:\n", zero_array_10)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
size = 5  # example size
border_array = np.ones((size, size))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)

Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.42397401 0.32258055 0.18668373 0.47242967 0.25330777 0.47191373
 0.13927985 0.64298465 0.43664656 0.57107302 0.06103015 0.5426898
 0.03740793 0.44693163 0.85888057 0.33019821 0.80808148 0.55384685
 0.69702251 0.34846362 0.81824476 0.8348029  0.09291114 0.28916585
 0.18127396 0.50064491 0.49711562 0.08129378 0.30455245 0.5935516 ]
Mean of random array: 0.426632775605664

10x10 random array:
 [[0.84002911 0.96916677 0.78087634 0.01816332 0.58242734 0.8943217
  0.11539766 0.45577477 0.38836132 0.0685351 ]
 [0.83000397 0.92310621 0.15939922 0.03976549 0.42262789 0.46870427
  0.59818607 0.5002022  0.97243278 0.26909571]
 [0.24611269 0.62974528 0.57787339 0.91675211 0.86849106 0.48158378
  0.30026296 0.8370198  0.5822

### **Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nx - y:\n", sub_xy)

# 3. Multiply the array with an integer (e.g., 3)
mul_x = x * 3
print("\nx * 3:\n", mul_x)

# 4. Find the square of each element of the array
square_x = x**2
print("\nx squared:\n", square_x)

# 5. Dot product
dot_vw = np.dot(v, w)# vectors
dot_xv = np.dot(x, v)# matrix and vector
dot_xy = np.dot(x, y) # matrices
print("\nDot product v·w:", dot_vw)
print("Dot product x·v:\n", dot_xv)
print("Dot product x·y:\n", dot_xy)

# 6. Concatenate
concat_xy_row = np.concatenate((x, y), axis=0)# along rows
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)# along columns
print("\nConcatenate x and y along rows:\n", concat_xy_row)
print("\nConcatenate v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v (expect error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
    print("\nError when concatenating x and v:\n", concat_xv_error)

x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

x squared:
 [[ 1  4]
 [ 9 25]]

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


### **Problem - 4: Matrix Operations:**

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

# 1. Prove A · A^(-1) = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A · A^(-1):\n", identity_check)

# Check if it's close to identity matrix
print("Is close to identity?:", np.allclose(identity_check, np.eye(2)))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("AB == BA?:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T?:", np.allclose(AB_T, BT_AT))



# Solve the system of linear equations using inverse method
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Using inverse: X = A^(-1) · B
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("\nSolution of the system [x, y, z]:\n", X)

A · A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is close to identity?: True

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA?: False

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T?: True

Solution of the system [x, y, z]:
 [ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy?

### 1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [ ]:
import time
import numpy as np

# Create two large lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# 1. Element-wise addition using Python lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
list_time = end_time - start_time
print("Time taken using Python lists: {:.6f} seconds".format(list_time))

# 2. Element-wise addition using NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken using NumPy arrays: {:.6f} seconds".format(numpy_time))

Time taken using Python lists: 0.109412 seconds
Time taken using NumPy arrays: 0.003884 seconds



### 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two large lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# 1. Element-wise multiplication using Python lists
start_time = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
list_time = end_time - start_time
print("Time taken using Python lists: {:.6f} seconds".format(list_time))

# 2. Element-wise multiplication using NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
array_mul = array1 * array2
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken using NumPy arrays: {:.6f} seconds".format(numpy_time))

Time taken using Python lists: 0.114259 seconds
Time taken using NumPy arrays: 0.004099 seconds



### 3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [ ]:
import time
import numpy as np

# Create two large lists/arrays
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# 1. Dot product using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
list_time = end_time - start_time
print("Time taken using Python lists: {:.6f} seconds".format(list_time))

# 2. Dot product using NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken using NumPy arrays: {:.6f} seconds".format(numpy_time))

Time taken using Python lists: 0.110517 seconds
Time taken using NumPy arrays: 0.001790 seconds



### 4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create two 1000x1000 matrices using lists
size = 1000
# Python lists
matrix1_list = [[i + j for j in range(size)] for i in range(size)]
matrix2_list = [[i - j for j in range(size)] for i in range(size)]

# NumPy arrays
matrix1_np = np.array(matrix1_list)
matrix2_np = np.array(matrix2_list)

# 1. Matrix multiplication using Python lists (nested loops)
start_time = time.time()

result_list = [[0]*size for _ in range(size)]
for i in range(size):
    for j in range(size):
        sum_val = 0
        for k in range(size):
            sum_val += matrix1_list[i][k] * matrix2_list[k][j]
        result_list[i][j] = sum_val

end_time = time.time()
list_time = end_time - start_time
print("Time taken using Python lists (1000x1000): {:.2f} seconds".format(list_time))

# 2. Matrix multiplication using NumPy
start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken using NumPy arrays (1000x1000): {:.2f} seconds".format(numpy_time))

Time taken using Python lists (1000x1000): 349.07 seconds
Time taken using NumPy arrays (1000x1000): 1.22 seconds
